format = """
$git_branch $git_status
[╭─ ](#ffffff)$username $hostname $directory  $fill $php $python
[╰─λ ](#ffffff)
"""

right_format = """
$cmd_duration
"""


# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#e06c75"
style_root = "bg:#9A348E"
format = '[$user]($style)'

[directory]
# style = "bg:#DA627D"
format = "in [ $path ]($style)"
# truncation_length = 0
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙"
"Documentos" = "󰈙 "
"Downloads" = " "
"Descargas" = " "
"Music" = " "
"Musica" = " "
"Pictures" = " "
"Imagenes" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[hostname]
ssh_only = false
format = "at [$hostname]($style)"
trim_at = "-"
style = "bold purple"
disabled = false

[cmd_duration]
min_time = 0
format = "took ~ [$duration](bold yellow) "

[fill]
symbol = " "
# style = "bold green"

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[php]
symbol = ""
# style = ""
format = ' [$symbol ($version) ]($style)'

[python]
symbol = " "

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "fg:#61afef"
#format = '[ $symbol $branch ]($style)'
format = " [($symbol $branch)](fg:bold purple)[( {:$remote_name/$remote_branch})]($style) "
always_show_remote = true

[git_status]
# style = "bg:#FCA17D"
modified = " ($count) "
deleted = " ($count) "
behind = " ($count) "
ahead = " ($count) "
staged = " ($count) "
untracked = " ($count) " 
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
