#!/bin/bash
#Author : Sevensuii <doroshyefimov@gmail.com>

# This script polls the battery status and prints out the
# the corresponding icon according the battery charge status.
# Use this when `bat` or `bat-asus-battery` commands are installed

#bat_power=$(awk '{print $1*10^-6 "W"}' /sys/class/power_supply/BAT0/power_now)
bat_power=$(cat /sys/class/power_supply/BAT0/power_now | awk '{printf("%.1f \n",$1*10^-6)}')
bat_power=$(echo $bat_power | xargs)
battery_status=$(bat-asus-battery -c)

if [[ "${battery_status}" -ge 95 ]] ; then
    bat_icon=""
elif [[ "${battery_status}" -ge 75 ]] ; then
    bat_icon=""
elif [[ "${battery_status}" -ge 50 ]] ; then
    bat_icon=""
elif [[ "${battery_status}" -ge 25 ]] ; then
    bat_icon=""
else
    bat_icon=""
fi

charge_status=$(bat-asus-battery -s)

if [[ "${charge_status}" == "Charging" ]] ; then
    bat_icon+=""
fi

printf "%s" "${bat_icon}${battery_status}% ${bat_power}W"
