#!/bin/bash 

layout=$(setxkbmap -query | grep layout | cut -f 2 -d ':' | xargs)

if [[ $layout == "us" ]]; then
    setxkbmap es
    #notify-send ES
else
    setxkbmap us
    #notify-send US
fi
#echo $layout
printf "%s" "${layout}"
